# Generated by Django 2.0.5 on 2018-05-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo_Item',
            new_name='TodoItem',
        ),
        migrations.RemoveField(
            model_name='jobstatus',
            name='todo_list',
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('First Contact', 'First Contact'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='todo_list',
            field=models.ManyToManyField(to='seekr.TodoItem'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='JobStatus',
        ),
    ]
