# Generated by Django 2.0.5 on 2018-05-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekr', '0003_auto_20180508_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='glassdoor_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('First Contact', 'First Contact'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
