# Generated by Django 2.0.5 on 2018-05-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekr', '0007_auto_20180510_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='todo_list',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='seekr.Job'),
        ),
    ]
